---
apiVersion: v1
kind: Namespace
metadata:
  name: central-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: le-dns01
  namespace: central-tls
spec:
  acme:
    email: "sasswartcdk@protonmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: sasswartcdk@protonmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ninjhah-cert
  namespace: central-tls
spec:
  dnsNames:
    - ninjhah.co.za
  secretName: ninjhah-cert-secret
  issuerRef:
    name: le-dns01