---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.namespace }}-volume
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: "/mnt/volume_lon1_01/{{ .Values.namespace }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namespace }}-volume
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi